-- Database schema for Terre d'Oliva.
-- Run in the Supabase SQL Editor.

-- Order status codes. The database stores stable English codes; each
-- frontend translates them for its users.
create type public.order_status as enum ('processing', 'shipped', 'delivered', 'cancelled');

-- Orders placed by logged-in users
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  full_name text not null,
  email text not null,
  phone text not null,
  address text not null,
  city text not null,
  postal_code text not null,
  status public.order_status not null default 'processing',
  total_amount numeric(10,2) not null,
  payment_method text not null
);

-- Products of each order, with name and price as paid at checkout
create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id integer not null,
  name text not null,
  price numeric(10,2) not null check (price >= 0),
  quantity integer not null check (quantity > 0)
);

-- Row Level Security: everything is denied until a policy allows it
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Policies: logged-in users can read and create only their own orders.
-- No update/delete: order status is managed by the shop, and orders are
-- kept as a record (cancelled orders get status 'cancelled').
create policy "Users can view their own orders"
on public.orders for select
to authenticated
using (user_id = (select auth.uid()));

create policy "Users can create their own orders"
on public.orders for insert
to authenticated
with check (user_id = (select auth.uid()));

create policy "Users can view items of their own orders"
on public.order_items for select
to authenticated
using (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = (select auth.uid())
  )
);

create policy "Users can add items to their own orders"
on public.order_items for insert
to authenticated
with check (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = (select auth.uid())
  )
);

-- Product catalog. Ids are kept from the original products.json, so
-- product_id values in existing orders keep pointing to the right product.
create table public.products (
  id integer primary key generated by default as identity,
  name text not null,
  price numeric(10,2) not null check (price >= 0),
  description text not null,
  category text not null,
  image text not null,
  -- Out-of-stock products stay visible in the catalog but cannot be ordered
  is_available boolean not null default true
);

alter table public.products enable row level security;

-- Everyone, including visitors who are not logged in, can browse the catalog.
-- No insert/update/delete from the storefront.
create policy "Anyone can view products"
on public.products for select
to anon, authenticated
using (true);

-- Run after seed.sql: existing order_items must already match a product.
-- No on delete cascade: a product that appears in orders cannot be deleted.
alter table public.order_items
add constraint order_items_product_id_fkey
foreign key (product_id) references public.products(id);

-- Creates an order and its items in a single transaction.
-- The client sends only customer details and, for each item, product_id and
-- quantity: user, prices, names and total are taken from the database, so they
-- cannot be tampered with from the browser.
-- Keep the shipping rule in sync with the Checkout page (shippingCost).
create or replace function public.create_order(
  p_full_name text,
  p_email text,
  p_phone text,
  p_address text,
  p_city text,
  p_postal_code text,
  p_payment_method text,
  p_items jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_order_id uuid;
  v_subtotal numeric(10,2);
  v_shipping numeric(10,2);
  v_unavailable text;
begin
  if auth.uid() is null then
    raise exception 'User must be logged in to place an order';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Order must contain at least one item';
  end if;

  -- Every product_id must exist in the catalog
  if exists (
    select 1
    from jsonb_array_elements(p_items) as item
    left join public.products as product
      on product.id = (item ->> 'product_id')::integer
    where product.id is null
  ) then
    raise exception 'Order contains an unknown product';
  end if;

  -- Out-of-stock products cannot be ordered. The error code is matched by the
  -- client, and the names of the unavailable products are sent as detail.
  select string_agg(product.name, ', ')
  into v_unavailable
  from jsonb_array_elements(p_items) as item
  join public.products as product
    on product.id = (item ->> 'product_id')::integer
  where not product.is_available;

  if v_unavailable is not null then
    raise exception 'PRODUCT_UNAVAILABLE' using detail = v_unavailable;
  end if;

  -- Subtotal from the real catalog prices
  select sum(product.price * (item ->> 'quantity')::integer)
  into v_subtotal
  from jsonb_array_elements(p_items) as item
  join public.products as product
    on product.id = (item ->> 'product_id')::integer;

  v_shipping := case when v_subtotal >= 50 then 0 else 6.90 end;

  insert into public.orders (
    user_id, full_name, email, phone, address, city, postal_code,
    total_amount, payment_method
  )
  values (
    auth.uid(), p_full_name, p_email, p_phone, p_address, p_city,
    p_postal_code, v_subtotal + v_shipping, p_payment_method
  )
  returning id into v_order_id;

  -- Name and price are copied from the catalog as a snapshot of this order
  insert into public.order_items (order_id, product_id, name, price, quantity)
  select
    v_order_id,
    product.id,
    product.name,
    product.price,
    (item ->> 'quantity')::integer
  from jsonb_array_elements(p_items) as item
  join public.products as product
    on product.id = (item ->> 'product_id')::integer;

  return v_order_id;
end;
$$;

-- Only logged-in users can call the function
revoke execute on function public.create_order from public, anon;
grant execute on function public.create_order to authenticated;

